// Automatically generated mappings for Pooja images (Local HD Assets)
window.SERVICE_IMAGES = {
  "aksharabhyasam": "assets/images/aksharabhyasam.jpg",
  "annaprasanam": "assets/images/annaprasanam.png",
  "barasala": "assets/images/barasala.png",
  "barasala-namakaranam": "assets/images/barasala.png",
  "bhima-ratha-shanti": "assets/images/homam.png",
  "shashti-abda-poorthi": "assets/images/homam.png",
  "sashtiapthapoorthi": "assets/images/homam.png",
  "satabhishekam": "assets/images/homam.png",
  "sathabhishekam": "assets/images/homam.png",
  "seemantham": "assets/images/seemantham.png",
  "nischitartham": "assets/images/nischitartham.png",
  "gruhapravesam": "assets/images/gruhapravesam.png",
  "karna-vedha": "assets/images/karna_vedha.png",
  "marriage": "assets/images/marriage.png",
  "upanayanam": "assets/images/upanayanam.png",
  "ayudha-pooja": "assets/images/ayudha_pooja.png",
  "durga-pooja": "assets/images/devi_default.png",
  "ganapati-pooja": "assets/images/ganapati_pooja.png",
  "new-vehicle-pooja": "assets/images/ayudha_pooja.png",
  "rudrabhishekam-pooja": "assets/images/rudrabhishekam.png",

  // 7 Pashupatham Specific Unique Images
  "vara-pashupatham": "assets/images/vara_pashupatham.png",
  "kanya-pashupatham": "assets/images/kanya_pashupatham.png",
  "vijay-pashupatham": "assets/images/vijay_pashupatham.png",
  "aarogya-pashupatham": "assets/images/aarogya_pashupatham.png",
  "dhanvantari-pashupatham": "assets/images/dhanvantari_pashupatham.png",
  "kubera-pashupatham": "assets/images/kubera_pashupatham.png",
  "kalyanam-pashupatham": "assets/images/kalyana_pashupatham.png",

  "astrologer": "assets/images/astrologer.png",
  "fix-your-muhurat": "assets/images/astrologer.png",
  "fix-your-muhurtham": "assets/images/astrologer.png",
  "saraswathi-pooja": "assets/images/devi_default.png",
  "satyanarayana-pooja": "assets/images/satyanarayana_pooja.png",
  "ganapathi-homam": "assets/images/ganapati_pooja.png",
  "chandi-homam": "assets/images/chandi_homam.png",
  "navagraha-homam": "assets/images/homam.png",
  "bhoomi-pooja": "assets/images/vastu_shanti.png",
  "vastu-shanti-pooja": "assets/images/vastu_shanti.png",
  "varalakshmi-vratham": "assets/images/varalakshmi_vratham.png",
  "lakshmi-pooja": "assets/images/varalakshmi_vratham.png",

  // Ancestor & Pitru Ritual Specific HD Images
  "annadanam-for-brahmins": "assets/images/brahmin_bhojan.png",
  "hindi-brahmins-for-bhojan": "assets/images/brahmin_bhojan.png",
  "hindi-swayampaka-seedha-daan-for-brahmins": "assets/images/brahmin_bhojan.png",
  "hindi-garud-puran-path": "assets/images/garud_puran.png",
  "tarpanam-hiranya-shradham": "assets/images/tarpanam.png",
  "hindi-amavasya-tarpan": "assets/images/tarpanam.png",
  "hindi-asthi-visarjan": "assets/images/asthi_visarjan.png",
  "hindi-antim-sanskar-last-rites": "assets/images/antim_sanskar.png",
  "pitru-paksha-taddinam": "assets/images/shradh_pujan.png",
  "samvatsarikam": "assets/images/shradh_pujan.png",
  "taddinam": "assets/images/shradh_pujan.png",
  "hindi-barsi-ceremony": "assets/images/shradh_pujan.png",
  "hindi-pitru-paksha-mahalaya-shradh-puja": "assets/images/shradh_pujan.png",
  "hindi-shradh": "assets/images/shradh_pujan.png"
};

// 43 Authentic Photos from assets/images/Vedicpoojapandi folder
window.MY_GALLERY_IMAGES = [
  { id: 'img-wa00', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0000.jpg', title: 'Maha Rudrabhishekam Linga Alankaram', category: 'Rudrabhishekam & Pashupatham', tag: 'Rudrabhishekam' },
  { id: 'img-wa02', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0002.jpg', title: 'Veda Patashala Pandits Chanting Mantras', category: 'Divine Priests', tag: 'Vedic Priests' },
  { id: 'img-wa05', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0005.jpg', title: 'Grand Chandi Homam Sacred Fire', category: 'Homams & Yagnas', tag: 'Homam' },
  { id: 'img-wa21', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0021.jpg', title: 'Vara Pashupatha Sacred Mandala Sthapana', category: 'Rudrabhishekam & Pashupatham', tag: 'Vara Pashupatham' },
  { id: 'img-wa22', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0022.jpg', title: 'Kanya Pashupatha Abhishekam Ritual', category: 'Rudrabhishekam & Pashupatham', tag: 'Kanya Pashupatham' },
  { id: 'img-wa23', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0023.jpg', title: 'Vijaya Pashupatha Homam Victory Yagna', category: 'Rudrabhishekam & Pashupatham', tag: 'Vijaya Pashupatham' },
  { id: 'img-wa24', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0024.jpg', title: 'Aarogya Pashupatha Divine Healing Abhishekam', category: 'Rudrabhishekam & Pashupatham', tag: 'Aarogya Pashupatham' },
  { id: 'img-wa25', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0025.jpg', title: 'Dhanvantari Pashupatha Health Blessing', category: 'Rudrabhishekam & Pashupatham', tag: 'Dhanvantari Pashupatham' },
  { id: 'img-wa26', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0026.jpg', title: 'Kubera Pashupatha Wealth & Abundance Homam', category: 'Rudrabhishekam & Pashupatham', tag: 'Kubera Pashupatham' },
  { id: 'img-wa27', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0027.jpg', title: 'Kalyana Pashupatha Relationship Bliss Worship', category: 'Rudrabhishekam & Pashupatham', tag: 'Kalyana Pashupatham' },
  { id: 'img-wa28', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0028.jpg', title: 'Authentic Astrologer Horoscope Consultation', category: 'Astrologer & Rituals', tag: 'Astrologer' },
  { id: 'img-wa30', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0030.jpg', title: 'Satyanarayana Vratham Flower Alankaram', category: 'Sacred Ceremonies', tag: 'Satyanarayana' },
  { id: 'img-wa31', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0031.jpg', title: 'Gruhapravesam Vastu Kalash Pratishtha', category: 'Sacred Ceremonies', tag: 'Gruhapravesam' },
  { id: 'img-wa32', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0032.jpg', title: 'Navagraha Shanti Havan Ahuti Offering', category: 'Homams & Yagnas', tag: 'Navagraha Homam' },
  { id: 'img-wa33', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0033.jpg', title: 'Vedic Vivah Sacred Saptapadi Ceremony', category: 'Sacred Ceremonies', tag: 'Marriage' },
  { id: 'img-wa34', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0034.jpg', title: 'Maha Lakshmi Kumkumarchana Ritual', category: 'Sacred Ceremonies', tag: 'Lakshmi Pooja' },
  { id: 'img-wa36', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0036.jpg', title: 'Veda Chanting by Senior Acharyas', category: 'Divine Priests', tag: 'Vedic Priests' },
  { id: 'img-wa37', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0037.jpg', title: 'Ganapathi Homam Modak & Ghee Offerings', category: 'Homams & Yagnas', tag: 'Ganapathi Homam' },
  { id: 'img-wa38', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0038.jpg', title: 'Vastu Shanti Purusha Sthapana Ritual', category: 'Sacred Ceremonies', tag: 'Vastu Shanti' },
  { id: 'img-wa39', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0039.jpg', title: 'Shiva Linga Milk & Honey Milk Abhishekam', category: 'Rudrabhishekam & Pashupatham', tag: 'Rudrabhishekam' },
  { id: 'img-wa40', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0040.jpg', title: 'Upanayanam Sacred Thread Yajnopavita', category: 'Sacred Ceremonies', tag: 'Upanayanam' },
  { id: 'img-wa41', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0041.jpg', title: 'Ayushya Homam Longevity Prayer Ritual', category: 'Homams & Yagnas', tag: 'Ayushya Homam' },
  { id: 'img-wa42', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0042.jpg', title: 'Shyamala Devi Siddha Yagna', category: 'Homams & Yagnas', tag: 'Shyamala Homam' },
  { id: 'img-wa43', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0043.jpg', title: 'Sudarsana Homam Protection Fire Ritual', category: 'Homams & Yagnas', tag: 'Sudarsana Homam' },
  { id: 'img-wa44', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0044.jpg', title: 'Astrologer Janam Kundali Matching Chart', category: 'Astrologer & Rituals', tag: 'Astrologer' },
  { id: 'img-wa45', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0045.jpg', title: 'Varalakshmi Vratham Sacred Toranam', category: 'Sacred Ceremonies', tag: 'Varalakshmi' },
  { id: 'img-wa46', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0046.jpg', title: 'Dhanvantari Health Havan Herbs Offering', category: 'Homams & Yagnas', tag: 'Dhanvantari' },
  { id: 'img-wa47', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0047.jpg', title: 'Saraswathi Vidya Pooja Books Blessing', category: 'Sacred Ceremonies', tag: 'Saraswathi' },
  { id: 'img-wa52', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0052.jpg', title: 'Bhoomi Pujan Silver Snake & Coin Placement', category: 'Sacred Ceremonies', tag: 'Bhoomi Puja' },
  { id: 'img-wa53', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0053.jpg', title: 'Grand Temple Mandap Setup for Pooja', category: 'Divine Priests', tag: 'Sacred Setup' },
  { id: 'img-wa54', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0054.jpg', title: 'Veda Patashala Certified Priests Group', category: 'Divine Priests', tag: 'Vedic Priests' },
  { id: 'img-wa55', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0055.jpg', title: 'Maha Mrityunjaya Jaap Healing Fire', category: 'Homams & Yagnas', tag: 'Mrityunjaya' },
  { id: 'img-wa56', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0056.jpg', title: 'Kanya Pashupatha Special Aradhana', category: 'Rudrabhishekam & Pashupatham', tag: 'Kanya Pashupatham' },
  { id: 'img-wa57', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0057.jpg', title: 'Vijaya Pashupatha Victory Yagna Flames', category: 'Rudrabhishekam & Pashupatham', tag: 'Vijaya Pashupatham' },
  { id: 'img-wa58', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0058.jpg', title: 'Aarogya Pashupatha Bilva Archana', category: 'Rudrabhishekam & Pashupatham', tag: 'Aarogya Pashupatham' },
  { id: 'img-wa59', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0059.jpg', title: 'Dhanvantari Herbs Infused Oil Abhishekam', category: 'Rudrabhishekam & Pashupatham', tag: 'Dhanvantari Pashupatham' },
  { id: 'img-wa60', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0060.jpg', title: 'Kubera Pashupatha Coin & Lotus Archana', category: 'Rudrabhishekam & Pashupatham', tag: 'Kubera Pashupatham' },
  { id: 'img-wa62', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0062.jpg', title: 'Kalyana Pashupatha Couple Mangala Sutra Blessing', category: 'Rudrabhishekam & Pashupatham', tag: 'Kalyana Pashupatham' },
  { id: 'img-wa63', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0063.jpg', title: 'Jyotishya Astrologer Horoscope Reading Session', category: 'Astrologer & Rituals', tag: 'Astrologer' },
  { id: 'img-wa65', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0065.jpg', title: 'Vara Pashupatha Grand Divine Blessing', category: 'Rudrabhishekam & Pashupatham', tag: 'Vara Pashupatham' },
  { id: 'img-wa67', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0067.jpg', title: 'Purnahuti Sacred Ghee Offering in Homam', category: 'Homams & Yagnas', tag: 'Homam' },
  { id: 'img-wa68', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0068.jpg', title: 'Priest Performing Sacred Aarti', category: 'Divine Priests', tag: 'Aarti' },
  { id: 'img-wa72', path: 'assets/images/Vedicpoojapandi/IMG-20260905-WA0072.jpg', title: 'Vedic Pooja Pandit Final Blessings & Prasadam', category: 'Divine Priests', tag: 'Vedic Priests' }
];

